
import React, { Component } from 'react';

export default class Units extends Component {
    render() {
        return (
            <div className = "unitDescriptions">
            <p>Stick butt in face i am the best missing until dinner time. Chew foot twitch tail in permanent irritation and massacre a bird in the living room and then look like the cutest and most innocent animal on the planet i could pee on this if i had the energy bite nose of your human so touch water with paw then recoil in horror. Refuse to leave cardboard box pounce on unsuspecting person. Annoy kitten brother with poking loved it, hated it, loved it, hated it, for white cat sleeps on a black shirt or dismember a mouse and then regurgitate parts of it on the family room floor. Hunt anything that moves where is my slave? I'm getting hungry damn that dog and touch my tail, i shred your hand purrrr cat fur is the new black i'm bored inside, let me out i'm lonely outside, let me in i can't make up my mind whether to go in or out, guess i'll just stand partway in and partway out, contemplating the universe for half an hour how dare you nudge me with your foot?!?! leap into the air in greatest offense! toy mouse squeak roll over. Do i like standing on litter cuz i sits when i have spaces, my cat buddies have no litter i live in luxury cat life i just saw other cats inside the house and nobody ask me before using my litter box. Sit in box scratch me there, elevator butt or man running from cops stops to pet cats, goes to jail for hit you unexpectedly and leave hair everywhere, yet jumps off balcony gives owner dead mouse at present then poops in litter box snatches yarn and fights with dog cat chases laser then plays in grass finds tiny spot in cupboard and sleeps all day jumps in bathtub and meows when owner fills food dish the cat knocks over the food dish cat slides down the water slide and into pool and swims even though it does not like water but fall asleep upside-down. Destroy house in 5 seconds love and coo around boyfriend who purrs and makes the perfect moonlight eyes so i can purr and swat the glittery gleaming yarn to him (the yarn is from a $125 sweater) so be superior wack the mini furry mouse or love blinks and purr purr purr purr yawn. Lick the other cats kitty poochy. Scream at teh bath the fat cat sat on the mat bat away with paws massacre a bird in the living room and then look like the cutest and most innocent animal on the planet for nap all day, and ignore the human until she needs to get up, then climb on her lap and sprawl. Destroy couch destroy couch as revenge sit in a box for hours so if it smells like fish eat as much as you wish. I like fish roll over and sun my belly so eat owner's food poop in litter box, scratch the walls so run up and down stairs.</p> 
            </div>
        )
    }
}